name: jaffle_shop
description: ''
version: 0.0.1
author: ashvjit+12@prophecy.io
language: sql
buildSystem: ''
buildSystemDetails:
  artefactID: jaffle_shop
  parentArtefactID: ''
  buildSystem: wheel
  author: null
  createdAt: '2023-03-30 08:17:21'
pipelines: {}
datasets: {}
templates: {}
jobs:
  jobs/Databricks_Jaffle_Shop_OAuth:
    name: Databricks_Jaffle_Shop_OAuth
    description: ''
    fabricUID: 68
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: null
    createdAt: '2024-11-15 14:11:47'
    author: ashvjit@prophecy.io
    models: []
    sqlProjects:
    - '274'
  jobs/Airflow_Jaffle_Shop_SQL_OAuth:
    name: Airflow_Jaffle_Shop_SQL_OAuth
    description: ''
    fabricUID: 99
    scheduler:
      OpenSource: {}
    cloudProvider: null
    jobSize: null
    scheduleCron: None
    timeout: null
    alerting:
      emails: ''
      onStart: false
      onSuccess: false
      onFailure: false
    pipelines: []
    jobClusterMode:
      clusterMode:
        Multi: {}
      clusterId: null
    enabled: false
    createdAt: '2024-11-15 14:13:12'
    author: ashvjit@prophecy.io
    models: []
    sqlProjects:
    - '274'
gemContainer:
  languageVersion: ''
  gemLibsVersion: ''
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2023-03-30 08:17:21'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels:
  .prophecy/metadata/sqlmodels/stg_orders:
    name: stg_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: ashvjit+12@prophecy.io
    files:
    - models/staging/stg_orders.sql
    - .prophecy/ide/models/stg_orders.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-03-30 09:05:35'
  .prophecy/metadata/sqlmodels/orders:
    name: orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: order_id
        dataType:
          type: Integer
      - name: customer_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
      - name: credit_card_amount
        dataType:
          type: Double
      - name: coupon_amount
        dataType:
          type: Double
      - name: bank_transfer_amount
        dataType:
          type: Double
      - name: gift_card_amount
        dataType:
          type: Double
      - name: amount
        dataType:
          type: Double
    description: This table has basic information about orders, as well as some derived
      facts based on payments
    author: ashvjit+12@prophecy.io
    files:
    - models/orders.sql
    - .prophecy/ide/models/orders.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-03-30 09:05:35'
  .prophecy/metadata/sqlmodels/customers:
    name: customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: first_order
        dataType:
          type: Date
      - name: most_recent_order
        dataType:
          type: Date
      - name: number_of_orders
        dataType:
          type: Bigint
      - name: customer_lifetime_value
        dataType:
          type: Double
    description: This table has basic information about a customer, as well as some
      derived facts based on a customer's orders
    author: ashvjit+12@prophecy.io
    files:
    - models/customers.sql
    - .prophecy/ide/models/customers.json
    - models/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-03-30 09:05:35'
  .prophecy/metadata/sqlmodels/stg_payments:
    name: stg_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: payment_id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Double
    description: null
    author: ashvjit+12@prophecy.io
    files:
    - models/staging/stg_payments.sql
    - .prophecy/ide/models/stg_payments.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-03-30 09:05:35'
  .prophecy/metadata/sqlmodels/stg_customers:
    name: stg_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: customer_id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
      - name: concat(first_name, last_name)
        dataType:
          type: String
    description: null
    author: ashvjit+12@prophecy.io
    files:
    - models/staging/stg_customers.sql
    - .prophecy/ide/models/stg_customers.json
    - models/staging/schema.yml
    sqlDependencies:
      models: []
      datasets: []
      seeds: []
      sources: []
      snapshots: []
    createdAt: '2023-03-30 09:05:35'
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds:
  .prophecy/metadata/sqlseeds/raw_customers:
    name: raw_customers
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: first_name
        dataType:
          type: String
      - name: last_name
        dataType:
          type: String
    description: null
    author: ashvjit@prophecy.io
    files:
    - seeds/raw_customers.csv
    createdAt: '2024-11-15 14:12:17'
  .prophecy/metadata/sqlseeds/raw_orders:
    name: raw_orders
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: user_id
        dataType:
          type: Integer
      - name: order_date
        dataType:
          type: Date
      - name: status
        dataType:
          type: String
    description: null
    author: ashvjit@prophecy.io
    files:
    - seeds/raw_orders.csv
    createdAt: '2024-11-15 14:12:17'
  .prophecy/metadata/sqlseeds/raw_payments:
    name: raw_payments
    schema:
      entityType: ''
      providerType: Databricks
      fields:
      - name: id
        dataType:
          type: Integer
      - name: order_id
        dataType:
          type: Integer
      - name: payment_method
        dataType:
          type: String
      - name: amount
        dataType:
          type: Integer
    description: null
    author: ashvjit@prophecy.io
    files:
    - seeds/raw_payments.csv
    createdAt: '2024-11-15 14:12:17'
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline:
  name: sqlPipeline
  description: null
  author: ashvjit+12@prophecy.io
  createdAt: '2023-03-30 08:17:21'
dependencies: '[]'
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
